### ISSUE TITLE
Face_Eye_Detection

### ISSUE THREAD

**Issue by Anubhavdevv** [akshitadixit/VCallZer#33]
Hi, I'm an LGM-SOC21 participant and I would like to contribute to your project
I want to add Face and Eye Detection folder in which I'll upload my face and eye detection code using open cv and Python 

@akshitadixit I will be happy if you assign this to me :))

**Comment by akshitadixit** [comment]
Hey **#** welcome to the repo, good to see you created your first issue here!

**Comment by Anubhavdevv** [comment]
Thank you for your comments kindly assign this issue to me :)

**Comment by akshitadixit** [comment]
@anubhav201241 I appreciate that you wish to contribute, but this issue is unrelated to the repository. VCallZer detects facial landmarks to project an outline of your face. And we are already using Dlib module which is very advanced when it comes to ladmark detection. I hope you realize we do not need face and eye detection.

However since you already have a fair understanding of open-cv and facial detection, why not try out #8 
You might actually find something and the issue also carries a lot of points :)
